### ISSUE TITLE
[feature request] API to work with video in form of numpy arrays

### ISSUE THREAD

**Issue by nikzasel** [AdamSpannbauer/python_video_stab#50]
It would be cool if you add some kind of API to stabilize video, which is being stored in form of an numpy array (4d for a colored video or 3d for a halftone video).

Thank you.

**Comment by AdamSpannbauer** [comment]
Thanks for submitting the feature request! I think this would be a great addition and force me to finally take care of #15.

**Comment by AdamSpannbauer** [comment]
### Todo list
* [ ] change current internal functionality to rely on a frame iterator/generator instead of looping with `cv2.VideoCapture` object in main process
* [ ] ideate best way to incorporate frames from user arrays
  * case of full video as numpy array should be easy case that can rely on frame iterator/generator mentioned in step 1
  * case of passing frames one at a time
    * append to a frame queue attribute?

**Comment by AdamSpannbauer** [comment]
want to complete #53 and #52 before starting on this

**Comment by mountainhound** [comment]
I would also love this feature.

Something like where you pass a np array and you need to pass a certain amount of initial frames to get a stabilized output. 
`
import cv2 as cv  
cap = cv.VideoCapture('vtest.avi')  
success, frame = cap.read()  
stabilizer = VidStab()  
output_array = stabilizer.stabilize_frame(input_frame=frame)
`

**OpenCV to BackgroundSubtractorMOG** does something similar - 

`import numpy as np  
import cv2 as cv  
cap = cv.VideoCapture('vtest.avi')  
fgbg = cv.bgsegm.createBackgroundSubtractorMOG()  
while(1):  
    ret, frame = cap.read()  
    fgmask = fgbg.apply(frame)  
    cv.imshow('frame',fgmask)  
    k = cv.waitKey(30) & 0xff  
    if k == 27:  
        break  
cap.release()  
cv.destroyAllWindows()`

**Comment by mountainhound** [comment]
I am happy to help with testing, or anything else you need.

**Comment by AdamSpannbauer** [comment]
@mountainhound I finally got around to working on this, and I just pushed a `VidStab.stabilize_frame()` method attempting to follow the pattern you proposed to the [nparray#50](https://github.com/AdamSpannbauer/python_video_stab/tree/nparray%2350) branch.

Below is an example script using the method.  There are still definitely kinks I need to work out on the backend, but I wanted to get your feedback on the proposed frontend of the implementation.  Please let me know any feedback you have.

Notes on implementation
* The output of `stabilize_frame()` is on an `N` frame delay where `N` is equal to the `smoothing_window` used.
* Like `createBackgroundSubtractorMOG`, `stabilize_frame()` returns an all `0` array while the process is warming up.
* `stabilize_frame()` can accept `None` as an input frame.  This is so the delayed frames can still be processed/returned.  When there are no frames left to process then `stabilize_frame()` returns `None`.


```python
import tempfile
import cv2
from vidstab import VidStab, layer_overlay, download_ostrich_video

# Download test video to stabilize
tmp_dir = tempfile.TemporaryDirectory()
ostrich_video_path = f'{tmp_dir.name}/vid.avi'
download_ostrich_video(ostrich_video_path)

# Init stabilizer and video reader
stabilizer = VidStab()
vidcap = cv2.VideoCapture(ostrich_video_path)

while True:
    grabbed_frame, frame = vidcap.read()

    if grabbed_frame:
        # Do frame pre-processing
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Pass frame to stabilizer even if frame is None
    stabilized_frame = stabilizer.stabilize_frame(input_frame=frame,
                                                  layer_func=layer_overlay,
                                                  border_size=100)

    # If stabilized_frame is None then there are no frames left to process
    if stabilized_frame is None:
        break

    # Display stabilized output
    cv2.imshow('Stabilized Frame', stabilized_frame)

    key = cv2.waitKey(5)
    if key == 27:
        break

vidcap.release()
cv2.destroyAllWindows()
```

**Comment by AdamSpannbauer** [comment]
* [ ] Finalize design/implementation of `VidStab.stabilize_frame()`.
* [ ] Write tests for `VidStab.stabilize_frame()`.
* [ ] Possibly, re-write main stabilization process to use `VidStab.stabilize_frame()` to simplify codebase.

**Comment by AdamSpannbauer** [comment]
I've merged #69 which addresses this issue.  See [docsite](https://adamspannbauer.github.io/python_video_stab) for [method documentation](https://adamspannbauer.github.io/python_video_stab/html/module_docs.html#vidstab.VidStab.stabilize_frame) and [example usage](https://adamspannbauer.github.io/python_video_stab/html/usage.html#stabilizing-a-frame-at-a-time).
